export const Products = [
  {
    category: "Smartphones",
    items: [
      {
        id: "SP001",
        title: "Ore Nova X1 5G",
        name: "Ore Nova X1 5G",
        available: true,
        imageurl:
          "https://images.pexels.com/photos/4526396/pexels-photo-4526396.jpeg?cs=srgb&dl=pexels-zion-4526396.jpg&fm=jpg",
        description:
          "Fast everyday smartphone with a clean display, strong battery life, and smooth performance.",
        overallSales: 1840,
        type: "import",
        normalPrice: 1290000,
        discountPrice: 1149000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.6,
        stockQty: 27,
        warranty: "12 months",
        condition: "new",
        colors: ["Black", "Blue"],
        features: ["5G", "Dual SIM", "Fast charging"],
        specs: {
          storage: "128GB",
          ram: "6GB",
          screen: "6.5-inch",
          camera: "50MP",
        },
      },
      {
        id: "SP002",
        title: "Ore Pulse Pro",
        name: "Ore Pulse Pro",
        available: true,
        imageurl:
          "https://images.pexels.com/photos/3945672/pexels-photo-3945672.jpeg?cs=srgb&dl=pexels-cottonbro-3945672.jpg&fm=jpg",
        description:
          "Slim smartphone with a bright screen and reliable battery for work and entertainment.",
        overallSales: 1520,
        type: "import",
        normalPrice: 1090000,
        discountPrice: 969000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.5,
        stockQty: 19,
        warranty: "12 months",
        condition: "new",
        colors: ["Silver", "Graphite"],
        features: ["Face unlock", "USB-C", "6.7-inch display"],
        specs: {
          storage: "128GB",
          ram: "4GB",
          screen: "6.7-inch",
          camera: "48MP",
        },
      },
      {
        id: "SP003",
        title: "Ore Max One",
        name: "Ore Max One",
        available: true,
        imageurl:
          "https://images.pexels.com/photos/11376175/pexels-photo-11376175.jpeg?cs=srgb&dl=pexels-spitak-11376175.jpg&fm=jpg",
        description:
          "A balanced smartphone with a premium feel, ideal for photos, social media, and daily use.",
        overallSales: 2055,
        type: "import",
        normalPrice: 1490000,
        discountPrice: 1339000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.7,
        stockQty: 14,
        warranty: "12 months",
        condition: "new",
        colors: ["Blue", "Gray"],
        features: ["Triple camera", "Long battery", "NFC"],
        specs: {
          storage: "256GB",
          ram: "8GB",
          screen: "6.6-inch",
          camera: "64MP",
        },
      },
      {
        id: "SP004",
        title: "Ore Prime S",
        name: "Ore Prime S",
        available: true,
        imageurl:
          "https://images.pexels.com/photos/14486282/pexels-photo-14486282.jpeg?cs=srgb&dl=pexels-zion-14486282.jpg&fm=jpg",
        description:
          "Clean, modern smartphone with a vivid display and smooth app switching.",
        overallSales: 1325,
        type: "in-store",
        normalPrice: 990000,
        discountPrice: 879000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.4,
        stockQty: 22,
        warranty: "6 months",
        condition: "new",
        colors: ["Orange", "Black"],
        features: ["Stereo sound", "Fast unlock", "Slim body"],
        specs: {
          storage: "128GB",
          ram: "6GB",
          screen: "6.4-inch",
          camera: "50MP",
        },
      },
      {
        id: "SP005",
        title: "Ore View Note",
        name: "Ore View Note",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real",
        description:
          "Large-screen phone made for watching, browsing, and multitasking.",
        overallSales: 960,
        type: "import",
        normalPrice: 1190000,
        discountPrice: 1049000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.3,
        stockQty: 11,
        warranty: "12 months",
        condition: "new",
        colors: ["Black"],
        features: ["Big display", "Long battery", "Dual camera"],
        specs: {
          storage: "128GB",
          ram: "6GB",
          screen: "6.8-inch",
          camera: "48MP",
        },
      },
      {
        id: "SP006",
        title: "Ore Zen Lite",
        name: "Ore Zen Lite",
        available: true,
        imageurl: "https://www.pinterest.com/ideas/smartphone/913778560918/",
        description:
          "Affordable smartphone option for daily communication and light apps.",
        overallSales: 740,
        type: "in-store",
        normalPrice: 720000,
        discountPrice: 659000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.1,
        stockQty: 34,
        warranty: "6 months",
        condition: "new",
        colors: ["Gray", "Gold"],
        features: ["Budget friendly", "Dual SIM", "Compact"],
        specs: {
          storage: "64GB",
          ram: "4GB",
          screen: "6.2-inch",
          camera: "13MP",
        },
      },
      {
        id: "SP007",
        title: "Ore Spark 5",
        name: "Ore Spark 5",
        available: true,
        imageurl:
          "https://www.pinterest.com/ideas/smartphone-gadget/954045571374/",
        description:
          "Sharp-looking budget smartphone for users who want value and style.",
        overallSales: 880,
        type: "import",
        normalPrice: 840000,
        discountPrice: 769000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.2,
        stockQty: 18,
        warranty: "12 months",
        condition: "new",
        colors: ["Green", "Black"],
        features: ["Fast charging", "Reliable battery", "Face unlock"],
        specs: {
          storage: "128GB",
          ram: "4GB",
          screen: "6.5-inch",
          camera: "16MP",
        },
      },
      {
        id: "SP008",
        title: "Ore Ultra Edge",
        name: "Ore Ultra Edge",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-2",
        description:
          "Premium-style phone with advanced performance and a sharp display.",
        overallSales: 2310,
        type: "import",
        normalPrice: 2190000,
        discountPrice: 1979000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.8,
        stockQty: 9,
        warranty: "12 months",
        condition: "new",
        colors: ["Titanium", "Black"],
        features: ["High refresh rate", "Fast processor", "Pro camera"],
        specs: {
          storage: "256GB",
          ram: "12GB",
          screen: "6.8-inch",
          camera: "108MP",
        },
      },
      {
        id: "SP009",
        title: "Ore Mini Go",
        name: "Ore Mini Go",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-3",
        description:
          "Compact smartphone for users who prefer a lighter, easy-to-carry device.",
        overallSales: 610,
        type: "in-store",
        normalPrice: 650000,
        discountPrice: 599000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.0,
        stockQty: 26,
        warranty: "6 months",
        condition: "new",
        colors: ["White", "Blue"],
        features: ["Pocket friendly", "Easy handling", "Good battery"],
        specs: {
          storage: "64GB",
          ram: "3GB",
          screen: "5.8-inch",
          camera: "12MP",
        },
      },
      {
        id: "SP010",
        title: "Ore Fusion 7",
        name: "Ore Fusion 7",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-4",
        description:
          "A practical smartphone for business, communication, and everyday tasks.",
        overallSales: 1195,
        type: "import",
        normalPrice: 980000,
        discountPrice: 889000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.4,
        stockQty: 15,
        warranty: "12 months",
        condition: "new",
        colors: ["Black", "Silver"],
        features: ["Dual camera", "Quick charge", "Strong signal"],
        specs: {
          storage: "128GB",
          ram: "6GB",
          screen: "6.5-inch",
          camera: "50MP",
        },
      },
      {
        id: "SP011",
        title: "Ore Nova Max",
        name: "Ore Nova Max",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-5",
        description:
          "Large, premium smartphone made for media lovers and power users.",
        overallSales: 1720,
        type: "import",
        normalPrice: 1690000,
        discountPrice: 1519000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.7,
        stockQty: 10,
        warranty: "12 months",
        condition: "new",
        colors: ["Blue", "Black"],
        features: ["Pro display", "Big battery", "Fast charging"],
        specs: {
          storage: "256GB",
          ram: "8GB",
          screen: "6.7-inch",
          camera: "64MP",
        },
      },
      {
        id: "SP012",
        title: "Ore Core 4",
        name: "Ore Core 4",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-6",
        description:
          "Entry-level phone for calls, chats, and basic apps at a friendly price.",
        overallSales: 520,
        type: "in-store",
        normalPrice: 540000,
        discountPrice: 489000,
        currency: "UGX",
        brand: "Ore",
        rating: 3.9,
        stockQty: 41,
        warranty: "6 months",
        condition: "new",
        colors: ["Black", "Gold"],
        features: ["Affordable", "Dual SIM", "Basic camera"],
        specs: {
          storage: "32GB",
          ram: "2GB",
          screen: "5.5-inch",
          camera: "8MP",
        },
      },
    ],
  },
  {
    category: "Audio",
    items: [
      {
        id: "AU001",
        title: "Ore BeatPods Pro",
        name: "Ore BeatPods Pro",
        available: true,
        imageurl:
          "https://images.pexels.com/photos/4526396/pexels-photo-4526396.jpeg?cs=srgb&dl=pexels-zion-4526396.jpg&fm=jpg",
        description:
          "Wireless earbuds with clear audio, touch controls, and a compact charging case.",
        overallSales: 2400,
        type: "import",
        normalPrice: 220000,
        discountPrice: 179000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.7,
        stockQty: 55,
        warranty: "12 months",
        condition: "new",
        colors: ["Black", "White"],
        features: ["Bluetooth 5.3", "Noise reduction", "Touch control"],
        specs: { battery: "30 hrs", connection: "Bluetooth", microphone: true },
      },
      {
        id: "AU002",
        title: "Ore BassMax Headphones",
        name: "Ore BassMax Headphones",
        available: true,
        imageurl:
          "https://images.pexels.com/photos/5208781/pexels-photo-5208781.jpeg?cs=srgb&dl=pexels-karola-g-5208781.jpg&fm=jpg",
        description:
          "Over-ear headphones with deep bass and comfortable ear cushions.",
        overallSales: 1680,
        type: "import",
        normalPrice: 260000,
        discountPrice: 219000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.6,
        stockQty: 31,
        warranty: "12 months",
        condition: "new",
        colors: ["Black"],
        features: ["Deep bass", "Foldable", "Long playtime"],
        specs: {
          battery: "40 hrs",
          connection: "Bluetooth / AUX",
          microphone: true,
        },
      },
      {
        id: "AU003",
        title: "Ore Sonic Mini Speaker",
        name: "Ore Sonic Mini Speaker",
        available: true,
        imageurl:
          "https://images.pexels.com/photos/3945672/pexels-photo-3945672.jpeg?cs=srgb&dl=pexels-cottonbro-3945672.jpg&fm=jpg",
        description:
          "Portable mini speaker with strong volume, ideal for small rooms and travel.",
        overallSales: 930,
        type: "in-store",
        normalPrice: 140000,
        discountPrice: 119000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.3,
        stockQty: 44,
        warranty: "6 months",
        condition: "new",
        colors: ["Gray", "Black"],
        features: ["Portable", "Loud sound", "USB rechargeable"],
        specs: {
          battery: "10 hrs",
          connection: "Bluetooth",
          waterproof: false,
        },
      },
      {
        id: "AU004",
        title: "Ore AirFlex Buds",
        name: "Ore AirFlex Buds",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-7",
        description:
          "Lightweight earbuds for music, calls, and daily commuting.",
        overallSales: 1210,
        type: "import",
        normalPrice: 190000,
        discountPrice: 149000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.4,
        stockQty: 38,
        warranty: "12 months",
        condition: "new",
        colors: ["White", "Pink"],
        features: ["Low latency", "Fast pairing", "Charging case"],
        specs: {
          battery: "24 hrs",
          connection: "Bluetooth 5.3",
          microphone: true,
        },
      },
      {
        id: "AU005",
        title: "Ore Studio Max",
        name: "Ore Studio Max",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-8",
        description:
          "Premium headphones tuned for strong clarity, bass, and comfort.",
        overallSales: 1020,
        type: "import",
        normalPrice: 310000,
        discountPrice: 269000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.6,
        stockQty: 17,
        warranty: "12 months",
        condition: "new",
        colors: ["Black", "Navy"],
        features: ["Noise isolation", "Soft padding", "Hi-fi sound"],
        specs: {
          battery: "35 hrs",
          connection: "Bluetooth / AUX",
          microphone: true,
        },
      },
      {
        id: "AU006",
        title: "Ore Pocket Boom",
        name: "Ore Pocket Boom",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-9",
        description:
          "Small speaker with big sound for casual listening anywhere.",
        overallSales: 760,
        type: "in-store",
        normalPrice: 110000,
        discountPrice: 89000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.2,
        stockQty: 60,
        warranty: "6 months",
        condition: "new",
        colors: ["Blue", "Black"],
        features: ["Ultra portable", "USB-C", "Hands-free calls"],
        specs: { battery: "8 hrs", connection: "Bluetooth", waterproof: false },
      },
      {
        id: "AU007",
        title: "Ore TuneFit Earbuds",
        name: "Ore TuneFit Earbuds",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-10",
        description: "Earbuds made for stable fit and everyday listening.",
        overallSales: 1450,
        type: "import",
        normalPrice: 175000,
        discountPrice: 139000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.4,
        stockQty: 42,
        warranty: "12 months",
        condition: "new",
        colors: ["Black", "White"],
        features: ["Stable fit", "Voice assistant support", "Compact case"],
        specs: { battery: "28 hrs", connection: "Bluetooth", microphone: true },
      },
      {
        id: "AU008",
        title: "Ore WaveBar Sound",
        name: "Ore WaveBar Sound",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-11",
        description:
          "Bluetooth soundbar for TV, laptop, and room audio upgrades.",
        overallSales: 690,
        type: "import",
        normalPrice: 420000,
        discountPrice: 369000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.5,
        stockQty: 13,
        warranty: "12 months",
        condition: "new",
        colors: ["Black"],
        features: ["Deep stereo", "Remote control", "Wall mount ready"],
        specs: {
          battery: null,
          connection: "Bluetooth / AUX / USB",
          microphone: false,
        },
      },
      {
        id: "AU009",
        title: "Ore ClearTalk Headset",
        name: "Ore ClearTalk Headset",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-12",
        description:
          "Work-friendly headset for calls, meetings, and online classes.",
        overallSales: 820,
        type: "in-store",
        normalPrice: 150000,
        discountPrice: 125000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.3,
        stockQty: 29,
        warranty: "6 months",
        condition: "new",
        colors: ["Black"],
        features: ["Mic boom", "Comfort fit", "Clear voice"],
        specs: { battery: "N/A", connection: "3.5mm / USB", microphone: true },
      },
      {
        id: "AU010",
        title: "Ore Pulse SoundCube",
        name: "Ore Pulse SoundCube",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-13",
        description: "Modern cube-style Bluetooth speaker with balanced sound.",
        overallSales: 1015,
        type: "import",
        normalPrice: 160000,
        discountPrice: 139000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.4,
        stockQty: 36,
        warranty: "12 months",
        condition: "new",
        colors: ["Gray", "Black"],
        features: ["Compact design", "Bluetooth", "Type-C charging"],
        specs: {
          battery: "12 hrs",
          connection: "Bluetooth",
          waterproof: false,
        },
      },
      {
        id: "AU011",
        title: "Ore BassMate Earbuds",
        name: "Ore BassMate Earbuds",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-14",
        description:
          "Bass-focused earbuds for energetic sound and compact carry.",
        overallSales: 1890,
        type: "import",
        normalPrice: 210000,
        discountPrice: 169000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.6,
        stockQty: 47,
        warranty: "12 months",
        condition: "new",
        colors: ["Black", "White"],
        features: ["Punchy bass", "Fast pairing", "Pocket case"],
        specs: {
          battery: "26 hrs",
          connection: "Bluetooth 5.3",
          microphone: true,
        },
      },
      {
        id: "AU012",
        title: "Ore AudioGo Speaker",
        name: "Ore AudioGo Speaker",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-15",
        description:
          "Entry-level speaker for music, podcasts, and small gatherings.",
        overallSales: 540,
        type: "in-store",
        normalPrice: 95000,
        discountPrice: 79000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.0,
        stockQty: 70,
        warranty: "6 months",
        condition: "new",
        colors: ["Blue", "Black"],
        features: ["Affordable", "Portable", "Rechargeable"],
        specs: { battery: "7 hrs", connection: "Bluetooth", waterproof: false },
      },
    ],
  },
  {
    category: "Accessories",
    items: [
      {
        id: "AC001",
        title: "Ore PowerBank 20K",
        name: "Ore PowerBank 20K",
        available: true,
        imageurl:
          "https://images.pexels.com/photos/5208781/pexels-photo-5208781.jpeg?cs=srgb&dl=pexels-karola-g-5208781.jpg&fm=jpg",
        description: "High-capacity power bank for phones and small gadgets.",
        overallSales: 2100,
        type: "import",
        normalPrice: 125000,
        discountPrice: 109000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.6,
        stockQty: 58,
        warranty: "12 months",
        condition: "new",
        colors: ["Black", "White"],
        features: ["20000mAh", "Dual output", "Fast charge"],
        specs: { capacity: "20000mAh", ports: 2, output: "22.5W" },
      },
      {
        id: "AC002",
        title: "Ore FastCharge Adapter",
        name: "Ore FastCharge Adapter",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-16",
        description: "Compact charging adapter for fast and safe charging.",
        overallSales: 1740,
        type: "in-store",
        normalPrice: 65000,
        discountPrice: 52000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.5,
        stockQty: 81,
        warranty: "6 months",
        condition: "new",
        colors: ["White"],
        features: ["Fast charging", "Overheat protection", "USB-C"],
        specs: { output: "20W", ports: 1, plugType: "UK" },
      },
      {
        id: "AC003",
        title: "Ore Flex Cable",
        name: "Ore Flex Cable",
        available: true,
        imageurl:
          "https://images.pexels.com/photos/32912404/pexels-photo-32912404.jpeg?cs=srgb&dl=pexels-busra-karabal-2148146457-32912404.jpg&fm=jpg",
        description:
          "Durable charging cable with reinforced ends for daily use.",
        overallSales: 2600,
        type: "in-store",
        normalPrice: 25000,
        discountPrice: 19000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.4,
        stockQty: 120,
        warranty: "3 months",
        condition: "new",
        colors: ["Black", "White"],
        features: ["Braided", "Fast sync", "Durable ends"],
        specs: { length: "1m", connector: "USB-C", dataTransfer: true },
      },
      {
        id: "AC004",
        title: "Ore Smart Watch Lite",
        name: "Ore Smart Watch Lite",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-17",
        description:
          "Stylish smartwatch with health tracking and notifications.",
        overallSales: 1360,
        type: "import",
        normalPrice: 185000,
        discountPrice: 159000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.5,
        stockQty: 25,
        warranty: "12 months",
        condition: "new",
        colors: ["Black", "Pink"],
        features: ["Heart rate", "Steps tracking", "Notifications"],
        specs: { battery: "5 days", display: "1.69-inch", waterproof: "IP67" },
      },
      {
        id: "AC005",
        title: "Ore Phone Grip Stand",
        name: "Ore Phone Grip Stand",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-18",
        description:
          "Handy phone grip and stand for better handling and viewing angles.",
        overallSales: 930,
        type: "in-store",
        normalPrice: 18000,
        discountPrice: 14000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.2,
        stockQty: 95,
        warranty: "3 months",
        condition: "new",
        colors: ["Black", "Blue"],
        features: ["360 stand", "Strong adhesive", "Pocket friendly"],
        specs: { material: "ABS", compatibility: "Universal", foldable: true },
      },
      {
        id: "AC006",
        title: "Ore Car Mount Pro",
        name: "Ore Car Mount Pro",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-19",
        description:
          "Strong car phone holder for navigation and hands-free driving.",
        overallSales: 1550,
        type: "import",
        normalPrice: 48000,
        discountPrice: 39000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.4,
        stockQty: 64,
        warranty: "6 months",
        condition: "new",
        colors: ["Black"],
        features: ["Strong grip", "360 rotation", "Dashboard mount"],
        specs: { mountType: "Dashboard / vent", compatibility: "Universal" },
      },
      {
        id: "AC007",
        title: "Ore Wireless Charger",
        name: "Ore Wireless Charger",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-20",
        description: "Fast wireless charging pad for supported devices.",
        overallSales: 820,
        type: "import",
        normalPrice: 99000,
        discountPrice: 82000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.3,
        stockQty: 39,
        warranty: "12 months",
        condition: "new",
        colors: ["White", "Black"],
        features: ["Qi charging", "Safe heat control", "Slim design"],
        specs: { output: "15W", cableIncluded: true, type: "Pad" },
      },
      {
        id: "AC008",
        title: "Ore Gaming Pad",
        name: "Ore Gaming Pad",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-21",
        description:
          "Mobile gaming controller with responsive buttons and ergonomic grip.",
        overallSales: 710,
        type: "import",
        normalPrice: 145000,
        discountPrice: 119000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.4,
        stockQty: 22,
        warranty: "6 months",
        condition: "new",
        colors: ["Black"],
        features: ["Ergonomic", "Low latency", "Stretch mount"],
        specs: { connection: "Bluetooth", compatibility: "Android / iPhone" },
      },
      {
        id: "AC009",
        title: "Ore USB Hub 4-in-1",
        name: "Ore USB Hub 4-in-1",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-22",
        description:
          "Useful USB hub for laptops, tablets, and accessory expansion.",
        overallSales: 640,
        type: "import",
        normalPrice: 78000,
        discountPrice: 62000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.2,
        stockQty: 43,
        warranty: "6 months",
        condition: "new",
        colors: ["Gray"],
        features: ["4 ports", "Plug and play", "Portable"],
        specs: { ports: 4, connector: "USB-C", powerDelivery: true },
      },
      {
        id: "AC010",
        title: "Ore Lens Kit",
        name: "Ore Lens Kit",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-23",
        description:
          "Clip-on lens set for better mobile photography and content creation.",
        overallSales: 560,
        type: "in-store",
        normalPrice: 60000,
        discountPrice: 49000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.1,
        stockQty: 29,
        warranty: "3 months",
        condition: "new",
        colors: ["Black"],
        features: ["Wide angle", "Macro lens", "Easy clip"],
        specs: {
          lenses: 3,
          material: "Aluminum + glass",
          compatibility: "Universal",
        },
      },
      {
        id: "AC011",
        title: "Ore Screen Guard Pack",
        name: "Ore Screen Guard Pack",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-24",
        description: "Tempered glass pack for protecting phone displays.",
        overallSales: 3050,
        type: "in-store",
        normalPrice: 30000,
        discountPrice: 22000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.6,
        stockQty: 150,
        warranty: "No warranty",
        condition: "new",
        colors: ["Clear"],
        features: ["Scratch resistant", "9H hardness", "Bubble free"],
        specs: {
          packSize: 2,
          compatibility: "Select models",
          thickness: "0.33mm",
        },
      },
      {
        id: "AC012",
        title: "Ore Bluetooth Tracker",
        name: "Ore Bluetooth Tracker",
        available: true,
        imageurl: "https://images.pexels.com/photos/537378view?not-real-25",
        description: "Small tracker for keys, bags, and gadget accessories.",
        overallSales: 410,
        type: "import",
        normalPrice: 70000,
        discountPrice: 59000,
        currency: "UGX",
        brand: "Ore",
        rating: 4.0,
        stockQty: 33,
        warranty: "6 months",
        condition: "new",
        colors: ["Black", "White"],
        features: ["Find my item", "App support", "Battery saving"],
        specs: {
          battery: "12 months",
          connection: "Bluetooth",
          range: "Up to 60m",
        },
      },
    ],
  },
];
